/**
 * Composable to manage available "things" (images and their corresponding words)
 * for the spell game.
 *
 * Images are stored in public/things/*.png|jpg
 * The filename (without extension) is the word to spell.
 */

import { ref, computed } from 'vue'

export type Difficulty = 'easy' | 'medium' | 'hard'

export interface Thing {
  word: string
  imagePath: string
  difficulty: Difficulty
}

/**
 * Helper function to determine word difficulty
 * - Easy: 3 letters or less, no diacritics
 * - Medium: 4 letters, no diacritics
 * - Hard: 5+ letters or contains diacritics
 */
const getDifficulty = (word: string): Difficulty => {
  const hasDiacritics = /[áäčďéěíľĺňóôŕřšťúůýž]/i.test(word)
  const length = word.length

  if (hasDiacritics || length > 4) {
    return 'hard'
  } else if (length > 3) {
    return 'medium'
  } else {
    return 'easy'
  }
}

// Hardcoded list of available things based on files in public/things/
// In a real build-time scenario, this could be generated by a Nuxt module or build script
const AVAILABLE_THINGS: Thing[] = [
  { word: 'lama', imagePath: '/things/lama.jpg', difficulty: getDifficulty('lama') },
  { word: 'láva', imagePath: '/things/lava.jpg', difficulty: getDifficulty('láva') },
  { word: 'les', imagePath: '/things/les.jpg', difficulty: getDifficulty('les') },
  { word: 'lev', imagePath: '/things/lev.png', difficulty: getDifficulty('lev') },
  { word: 'lov', imagePath: '/things/lov.jpg', difficulty: getDifficulty('lov') },
  { word: 'malá', imagePath: '/things/mala.jpg', difficulty: getDifficulty('malá') },
  { word: 'malina', imagePath: '/things/malina.jpg', difficulty: getDifficulty('malina') },
  { word: 'mama', imagePath: '/things/mama.png', difficulty: getDifficulty('mama') },
  { word: 'maslo', imagePath: '/things/maslo.jpg', difficulty: getDifficulty('maslo') },
  { word: 'osa', imagePath: '/things/osa.jpg', difficulty: getDifficulty('osa') },
  { word: 'slama', imagePath: '/things/slama.jpg', difficulty: getDifficulty('slama') },
  { word: 'sláva', imagePath: '/things/slava.jpg', difficulty: getDifficulty('sláva') },
  { word: 'sova', imagePath: '/things/sova.jpg', difficulty: getDifficulty('sova') },
]

export const useThings = () => {
  const things = ref<Thing[]>([...AVAILABLE_THINGS])

  const thingsCount = computed(() => things.value.length)

  /**
   * Get things filtered by difficulty
   */
  const getThingsByDifficulty = (difficulty: Difficulty): Thing[] => {
    return things.value.filter(thing => thing.difficulty === difficulty)
  }

  /**
   * Get count of things by difficulty
   */
  const getThingsCountByDifficulty = (difficulty: Difficulty): number => {
    return getThingsByDifficulty(difficulty).length
  }

  /**
   * Get a random thing from the available list, optionally filtered by difficulty
   */
  const getRandomThing = (difficulty?: Difficulty): Thing | null => {
    const availableThings = difficulty ? getThingsByDifficulty(difficulty) : things.value
    if (availableThings.length === 0) return null
    const randomIndex = Math.floor(Math.random() * availableThings.length)
    return availableThings[randomIndex] ?? null
  }

  /**
   * Get all available things
   */
  const getAllThings = (): Thing[] => {
    return [...things.value]
  }

  return {
    things: computed(() => things.value),
    thingsCount,
    getRandomThing,
    getAllThings,
    getThingsByDifficulty,
    getThingsCountByDifficulty,
  }
}
