/**
 * Composable to manage available "things" (images and their corresponding words)
 * for the spell game.
 *
 * Images are stored in public/things/*.png|jpg
 * The filename (without extension) is the word to spell.
 */

import { ref, computed } from 'vue'

export interface Thing {
  word: string
  imagePath: string
}

// Hardcoded list of available things based on files in public/things/
// In a real build-time scenario, this could be generated by a Nuxt module or build script
const AVAILABLE_THINGS: Thing[] = [
  { word: 'lama', imagePath: '/things/lama.jpg' },
  { word: 'lev', imagePath: '/things/lev.png' },
  { word: 'mama', imagePath: '/things/mama.png' },
]

export const useThings = () => {
  const things = ref<Thing[]>([...AVAILABLE_THINGS])

  const thingsCount = computed(() => things.value.length)

  /**
   * Get a random thing from the available list
   */
  const getRandomThing = (): Thing | null => {
    if (things.value.length === 0) return null
    const randomIndex = Math.floor(Math.random() * things.value.length)
    return things.value[randomIndex]
  }

  /**
   * Get all available things
   */
  const getAllThings = (): Thing[] => {
    return [...things.value]
  }

  return {
    things: computed(() => things.value),
    thingsCount,
    getRandomThing,
    getAllThings,
  }
}
